### PR TITLE
EZP-30875: Allow to run migrate command in --no-interaction mode

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
JIRA: https://jira.ez.no/browse/EZP-30875

### CODE REVIEW

**Comment by SerheyDolgushev** [comment]
@adamwojs please have a look.

**Comment by adamwojs** [comment]
This command is designed to work only in the interactive mode: user needs to be warned about the potential risk. If we would like to change it IMHO we should introduce `--force` flag similar to `doctrine:schema:update`.

**Comment by andrerom** [comment]
Afaik `--no-interaction` is something CLI user needs to specify right? So if this is being scripted the person doing so has already been made aware of the warning for need to do backups. Or is there a need to also need to use the force for this?

**Comment by Nattfarinn** [comment]
`--no-interaction` does not imply you're aware of consequences. It only means you don't want to be bothered with TTY questions about unspecified arguments and run command in a non-blocking way. If we remove interaction restriction, we'll need the `--force` parameter. This operation is irreversible and I would opt for a safe approach here. Just like aformentioned by @adamwojs `doctrine:schema:update`.

**Comment by SerheyDolgushev** [comment]
@Nattfarinn can you please review https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/18/commits/e9d67b3a5a85e1f440fdc3a178d8ac557343601b ?

**Comment by andrerom** [comment]
One thing: You meant this for 1.0 right @SerheyDolgushev? (aka for 2.5)

**Comment by SerheyDolgushev** [comment]
Yes, should I rebase this PR?

**Comment by andrerom** [comment]
yes please

**Comment by SerheyDolgushev** [comment]
@andrerom Done. It took a few minutes for GitHub to handle this :)

**Comment by andrerom** [comment]
@adamwojs Would you be able to handle the merge up whenever it fits?

**Comment by adamwojs** [comment]
Done.

**Pull request merged**
